{
 "title": "StreamLoom Markets",
 "panels": [
  {
   "title": "Ingested Trades",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(events_published_total[1m])"
    }
   ]
  },
  {
   "title": "ClickHouse Inserts Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(insert_latency_ms_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  }
 ]
}